info:
  application:
    name: ${spring.application.name}
    description: Auth Service for Domain Driven Deign LinkedHub
    version: 1.0.0
  env:
    enabled: true

server:
  port: 8091

spring:
  application:
    name: "auth-service"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: "postgres"
    password: "secret"

  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
    bus:
      enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: "localhost"
      port: 6379

  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false

jwt:
  secret:
    key: "blj8MNM/hiV/8XJ7kh9SuSOIiseqjSIlP+zLigU1N24kp0ISrFWbEQ=="
    expiration: 3600000 # 1 hour

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka"

logging:
  level:
    org.springframework.web: DEBUG



