info:
  application:
    name: ${spring.application.name}
    description: Gateway Service for Domain Driven Deign LinkedHub
    version: 1.0.0
  env:
    enabled: true

server:
  port: 8080

spring:
  application:
    name: "gateway-service"
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
    bus:
      enabled: true
      refresh:
        enabled: true

jwt:
  secret:
    key: "blj8MNM/hiV/8XJ7kh9SuSOIiseqjSIlP+zLigU1N24kp0ISrFWbEQ=="
    expiration: 3600000 # 1 hour


management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
#  file:
#    name: ./gateway-service/logs/gateway.log
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"