spring:
  application:
    name: eureka-service
server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

    service-url:
      default-zone: http://$localhost:8761/eureka/