server:
  port: 8888

spring:
  application:
    name: config-service

  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/phuquocchamp/ddd-linkedhub-config.git
          default-label: dev
          timeout: 5
          clone-on-start: true
          force-pull: true

      profile: dev

    bus:
      enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka